#:import Scene elements
#:import Action elements
#:import Character elements
#:import SceneHeading elements

# elements are implemented in elements.py


<Scene>:
    cols: 1
    touch_multiselect: True
    multiselect: True
    size_hint_y: None
    height: self.minimum_height
    canvas.before:
        Color:
            rgba: [1, 1, 1, 1]
        Rectangle:
            size: self.size
            pos: self.pos
    SceneHeading:
